CREATE TABLE STATUS(
	STATUS_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NAME VARCHAR(100)
);
CREATE TABLE USERS(
	USER_ID BIGINT  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NAME VARCHAR(100),
	PASSWORD VARCHAR(100),
	LOGIN VARCHAR(100),
	STATUS_REF BIGINT,
	CONSTRAINT USER_STATUS
      FOREIGN KEY(STATUS_REF) 
	  REFERENCES STATUS(STATUS_ID)
);
CREATE TABLE ROLES(
	ROLE_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NAME VARCHAR(100)
);
CREATE TABLE USER_ROLE(
	USER_REF BIGINT,
	ROLE_REF BIGINT,
	CONSTRAINT USER_ROLE_USER
      FOREIGN KEY(USER_REF) 
	  REFERENCES USERS(USER_ID),
	CONSTRAINT USER_ROLE_ROLE
      FOREIGN KEY(ROLE_REF) 
	  REFERENCES ROLES(ROLE_ID)
);
CREATE TABLE QSESSION(
	QSESSION_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	STATUS_REF BIGINT,
	USER_REF BIGINT,
	CURRENT_QUESTION_NUMBER SMALLINT,
	QUESTION_AMOUNT SMALLINT,
	TIME_REF BIGINT,
	CONSTRAINT QSESSION_STATUS
      FOREIGN KEY(STATUS_REF) 
	  REFERENCES STATUS(STATUS_ID),
	CONSTRAINT USER_QSESSION
      FOREIGN KEY(USER_REF) 
	  REFERENCES USERS(USER_ID)
);
CREATE TABLE QUESTION(
	QUESTION_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	QTEXT VARCHAR(100),
	ANSWER_REF BIGINT,
	STATUS_REF BIGINT,
	CONSTRAINT QUESTION_STATUS
      FOREIGN KEY(STATUS_REF) 
	  REFERENCES STATUS(STATUS_ID)
);

CREATE TABLE QUESTION_QSESSION(
	QUESTION_REF BIGINT,
	QSESSION_REF BIGINT,
	NUBMER_QUESTION SMALLINT,
	STATUS_REF BIGINT,
	CONSTRAINT QUESTION_QSESSION_QSESSION
      FOREIGN KEY(QSESSION_REF) 
	  REFERENCES QSESSION(QSESSION_ID),
	CONSTRAINT QUESTION_QSESSION_QUESTION
      FOREIGN KEY(QUESTION_REF) 
	  REFERENCES QUESTION(QUESTION_ID),
	CONSTRAINT QUESTION_QSESSION_STATUS
      FOREIGN KEY(STATUS_REF) 
	  REFERENCES STATUS(STATUS_ID)
);
CREATE TABLE ISESSION(
	ISESSION_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	STATUS_REF BIGINT,
	USER_REF BIGINT,
	CONSTRAINT ISESSIONS_STATUS
      FOREIGN KEY(STATUS_REF) 
	  REFERENCES STATUS(STATUS_ID),
	CONSTRAINT USER_ISESSION
      FOREIGN KEY(USER_REF) 
	  REFERENCES USERS(USER_ID)
);
CREATE TABLE ITEM(
	ITEM_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	ITEXT VARCHAR(100),
	PER_EXECUTED SMALLINT,
	SESSION_REF BIGINT,
	STATUS_REF BIGINT,
	CONSTRAINT ITEM_STATUS
      FOREIGN KEY(STATUS_REF) 
	  REFERENCES STATUS(STATUS_ID),
	CONSTRAINT QUESTION_SESSION
      FOREIGN KEY(SESSION_REF) 
	  REFERENCES SESSIONS(SESSION_ID)
);
CREATE TABLE ITEM_ISESSION(
	SESSION_REF BIGINT,
	ITEM_REF BIGINT,
	CONSTRAINT ITEM_SESSION_ITEM
		FOREIGN KEY (ITEM_REF)
		REFERENCES ITEM(ITEM_ID),
	CONSTRAINT ITEM_SESSION_SESSION
		FOREIGN KEY (SESSION_REF)
		REFERENCES SESSIONS(SESSION_ID)
);
CREATE TABLE THEME(
	THEME_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NAME VARCHAR(100)
);
CREATE TABLE ITEM_THEME(
	ITEM_REF BIGINT,
	THEME_REF BIGINT,
	CONSTRAINT ITEM_THEME_ITEM
      FOREIGN KEY(ITEM_REF) 
	  REFERENCES ITEM(ITEM_ID),
	CONSTRAINT ITEM_THEME_THEME
      FOREIGN KEY(THEME_REF) 
	  REFERENCES THEME(THEME_ID)
);
CREATE TABLE QUESTION_THEME(
	QUESTION_REF BIGINT,
	THEME_REF BIGINT,
	ANSWER_REF BIGINT,
	CONSTRAINT QUESTION_THEME_QUESTION
      FOREIGN KEY(QUESTION_REF) 
	  REFERENCES QUESTION(QUESTION_ID),
	CONSTRAINT QUESTION_THEME_THEME
      FOREIGN KEY(THEME_REF) 
	  REFERENCES THEME(THEME_ID)
);

CREATE TABLE ANSWER(
	ANSWER_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	ATEXT TEXT
);

CREATE TABLE QUESTION_ANSWER(
	QUESTION_REF BIGINT,
	ANSWER_REF BIGINT,
	CONSTRAINT QUESTION_ANSWER_QUESTION
	FOREIGN KEY (QUESTION_REF)
	REFERENCES QUESTION(QUESTION_ID),
	CONSTRAINT QUESTION_ANSWER_ANSWER
	FOREIGN KEY (ANSWER_REF)
	REFERENCES ANSWER(ANSWER_ID)
);

CREATE TABLE SKILL(
	SKILL_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NAME VARCHAR(100)
);

CREATE TABLE ITEM_SKILL(
	ITEM_REF BIGINT,
	SKILL_REF BIGINT,
	CONSTRAINT ITEM_SKILL_ITEM
      FOREIGN KEY(ITEM_REF) 
	  REFERENCES ITEM(ITEM_ID),
	CONSTRAINT ITEM_SKILL_SKILL
      FOREIGN KEY(SKILL_REF) 
	  REFERENCES SKILL(SKILL_ID)
);

CREATE TABLE TIMES(
	TIME_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NAME VARCHAR(100),
	DURATION BIGINT
);