INSERT INTO STATUS(NAME)
VALUES('ACTIVE'),
('NO_ACTIVE'),
('BEGINNER'),
('GOOD'),
('STRONG'),
('TRUE'),
('FALSE');

INSERT INTO USERS(NAME, PASSWORD, LOGIN, STATUS_REF)
VALUES('Valentyn Vrakin', '111', 'vvo12015', 1);

INSERT INTO ROLES(NAME)
VALUES('ADMIN');

INSERT INTO USER_ROLE(USER_REF, ROLE_REF)
VALUES(1, 1);

INSERT INTO ANSWER(ATEXT)
VALUES('TRUE'),
('NO'),
('FALSE'),
('BAD');

INSERT INTO QUESTION(QTEXT, ANSWER_REF, STATUS_REF)
VALUES('TEST', 1, 1);

INSERT INTO THEME(NAME)
VALUES ('TEST');

INSERT INTO QUESTION_THEME(QUESTION_REF, THEME_REF)
VALUES (1, 1);

INSERT INTO QUESTION_ANSWER(QUESTION_REF, ANSWER_REF)
VALUES(1, 1),
(1, 2),
(1, 3),
(1, 4);

